version: '3.9'
services:
  backend:
    build: .
    restart: always
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
   
  mongo:
    image: mongo
    ports:
      - 27017:27017
  