version: '3.3'
services:
  backend:
    build: .
    restart: always
    ports:
      - 4001:4001
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
    networks:
      - default
    
   
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - default

networks:
  default:
    

  
